### ISSUE TITLE
addition of a license

### ISSUE THREAD

**Issue by nbehrnd** [M-R-Schaefer/xyz2pov#1]
For an intended fork of the project, I would like to request the addition of a license.  This would then add a tag on the landing page of the project, as well as a dedicated license file in the project; both by a few clicks with a mouse.[[reference](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)]

**Comment by M-R-Schaefer** [comment]
Thank you for your interest.
This is one of the repositories I made while I was still new to software development and didn't know about how licensing works.
I should probably do that for all my old repose (or make them private).
I will gladly add a permissive license.

**Comment by nbehrnd** [comment]
This is good news. Thank you.
